version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: chedlyrebai_mysql
    environment:
      MYSQL_DATABASE: chedlyrebai_db
      MYSQL_USER: chedly
      MYSQL_PASSWORD: chedly
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: